// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/meta-ads": {
            "post": {
                "description": "Consulta dados do Meta Ads usando um token fornecido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Meta Ads API",
                "parameters": [
                    {
                        "description": "Token de acesso ao Meta Ads",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    }
                }
            }
        },
        "/api/meta-ads/metricas": {
            "get": {
                "description": "Consulta métricas específicas do Meta Ads usando um token fornecido via query parameter",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Meta Ads Métricas",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token de acesso ao Meta Ads",
                        "name": "token",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID da conta de anúncios (opcional)",
                        "name": "account_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "ID da campanha (opcional)",
                        "name": "campaign_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.MetaAdsResponse"
                        }
                    }
                }
            }
        },
        "/webhook/echo": {
            "post": {
                "description": "Retorna o mesmo payload recebido",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Echo webhook",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {}
                    }
                }
            }
        },
        "/webhook/hotmart": {
            "post": {
                "description": "Recebe notificações da Hotmart",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Webhook Hotmart",
                "parameters": [
                    {
                        "description": "Payload do webhook",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HotmartWebhook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.HotmartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.HotmartResponse"
                        }
                    }
                }
            }
        },
        "/webhook/kirvano": {
            "post": {
                "description": "Recebe notificações da Kirvano",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Webhook Kirvano",
                "parameters": [
                    {
                        "description": "Payload do webhook",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KirvanoWebhookBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KirvanoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.KirvanoResponse"
                        }
                    }
                }
            }
        },
        "/webhook/kiwify": {
            "post": {
                "description": "Recebe notificações da Kiwify",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Webhook Kiwify",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Assinatura para validação",
                        "name": "signature",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Payload do webhook",
                        "name": "webhook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KiwifyWebhook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KiwifyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.KiwifyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HotmartResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.HotmartWebhook": {
            "type": "object",
            "properties": {
                "affiliate": {
                    "description": "Presente apenas em abandono de carrinho",
                    "type": "boolean"
                },
                "affiliates": {
                    "description": "Opcional",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "affiliate_code": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        }
                    }
                },
                "buyer": {
                    "type": "object",
                    "properties": {
                        "address": {
                            "type": "object",
                            "properties": {
                                "country": {
                                    "type": "string"
                                },
                                "country_iso": {
                                    "type": "string"
                                }
                            }
                        },
                        "checkout_phone": {
                            "description": "Renomeado para phone em abandono de carrinho",
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "phone": {
                            "description": "Usado em abandono de carrinho",
                            "type": "string"
                        }
                    }
                },
                "buyer_ip": {
                    "description": "Presente apenas em abandono de carrinho",
                    "type": "string"
                },
                "commissions": {
                    "description": "Opcional em abandono de carrinho",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "currency_value": {
                                "type": "string"
                            },
                            "source": {
                                "type": "string"
                            },
                            "value": {
                                "type": "number"
                            }
                        }
                    }
                },
                "creation_date": {
                    "type": "integer"
                },
                "event": {
                    "type": "string"
                },
                "hottok": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "offer": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string"
                        }
                    }
                },
                "producer": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "product": {
                    "type": "object",
                    "properties": {
                        "has_co_production": {
                            "type": "boolean"
                        },
                        "id": {
                            "type": "integer"
                        },
                        "name": {
                            "type": "string"
                        },
                        "ucode": {
                            "description": "Opcional em alguns eventos",
                            "type": "string"
                        }
                    }
                },
                "purchase": {
                    "type": "object",
                    "properties": {
                        "approved_date": {
                            "type": "integer"
                        },
                        "checkout_country": {
                            "type": "object",
                            "properties": {
                                "iso": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            }
                        },
                        "full_price": {
                            "type": "object",
                            "properties": {
                                "currency_value": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        },
                        "offer": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                }
                            }
                        },
                        "order_bump": {
                            "type": "object",
                            "properties": {
                                "is_order_bump": {
                                    "type": "boolean"
                                },
                                "parent_purchase_transaction": {
                                    "type": "string"
                                }
                            }
                        },
                        "order_date": {
                            "type": "integer"
                        },
                        "original_offer_price": {
                            "type": "object",
                            "properties": {
                                "currency_value": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        },
                        "payment": {
                            "type": "object",
                            "properties": {
                                "installments_number": {
                                    "type": "integer"
                                },
                                "type": {
                                    "type": "string"
                                }
                            }
                        },
                        "price": {
                            "type": "object",
                            "properties": {
                                "currency_value": {
                                    "type": "string"
                                },
                                "value": {
                                    "type": "number"
                                }
                            }
                        },
                        "sckPaymentLink": {
                            "type": "string"
                        },
                        "status": {
                            "description": "APPROVED, DISPUTE, EXPIRED, etc",
                            "type": "string"
                        },
                        "transaction": {
                            "type": "string"
                        }
                    }
                },
                "subscription": {
                    "type": "object",
                    "properties": {
                        "plan": {
                            "type": "object",
                            "properties": {
                                "id": {
                                    "type": "integer"
                                },
                                "name": {
                                    "type": "string"
                                }
                            }
                        },
                        "status": {
                            "type": "string"
                        },
                        "subscriber": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "models.KirvanoResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.KirvanoWebhookBody": {
            "type": "object",
            "properties": {
                "checkout_id": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "type": "object",
                    "properties": {
                        "document": {
                            "type": "string"
                        },
                        "email": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        }
                    }
                },
                "event": {
                    "type": "string"
                },
                "event_description": {
                    "type": "string"
                },
                "payment": {
                    "type": "object",
                    "properties": {
                        "brand": {
                            "type": "string"
                        },
                        "finished_at": {
                            "type": "string"
                        },
                        "installments": {
                            "type": "integer"
                        },
                        "method": {
                            "type": "string"
                        }
                    }
                },
                "payment_method": {
                    "type": "string"
                },
                "products": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "description": {
                                "type": "string"
                            },
                            "id": {
                                "type": "string"
                            },
                            "is_order_bump": {
                                "type": "boolean"
                            },
                            "name": {
                                "type": "string"
                            },
                            "offer_id": {
                                "type": "string"
                            },
                            "offer_name": {
                                "type": "string"
                            },
                            "photo": {
                                "type": "string"
                            },
                            "price": {
                                "type": "string"
                            }
                        }
                    }
                },
                "sale_id": {
                    "description": "Atualizado para sale_id",
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "total_price": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "utm": {
                    "type": "object",
                    "properties": {
                        "src": {
                            "type": "string"
                        },
                        "utm_campaign": {
                            "type": "string"
                        },
                        "utm_content": {
                            "type": "string"
                        },
                        "utm_medium": {
                            "type": "string"
                        },
                        "utm_source": {
                            "type": "string"
                        },
                        "utm_term": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "models.KiwifyResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.KiwifyWebhook": {
            "type": "object",
            "properties": {
                "access_url": {
                    "type": "string"
                },
                "commissions": {
                    "type": "object",
                    "properties": {
                        "commissioned_stores": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "custom_name": {
                                        "type": "string"
                                    },
                                    "type": {
                                        "type": "string"
                                    },
                                    "value": {
                                        "type": "string"
                                    }
                                }
                            }
                        },
                        "currency": {
                            "type": "string"
                        }
                    }
                },
                "created_at": {
                    "type": "string"
                },
                "customer": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "phone_number": {
                            "type": "string"
                        }
                    }
                },
                "order_id": {
                    "type": "string"
                },
                "order_ref": {
                    "type": "string"
                },
                "order_status": {
                    "type": "string"
                },
                "payment": {
                    "type": "object",
                    "properties": {
                        "currency": {
                            "type": "string"
                        },
                        "installments": {
                            "type": "integer"
                        },
                        "method": {
                            "type": "string"
                        },
                        "processor_id": {
                            "type": "string"
                        },
                        "safe_status": {
                            "type": "string"
                        },
                        "status": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string"
                        }
                    }
                },
                "producer": {
                    "type": "object",
                    "properties": {
                        "email": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "product": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        },
                        "order_bump_id": {
                            "type": "string"
                        },
                        "price": {
                            "type": "string"
                        },
                        "quantity": {
                            "type": "integer"
                        },
                        "regular": {
                            "type": "boolean"
                        }
                    }
                },
                "store": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "name": {
                            "type": "string"
                        }
                    }
                },
                "subscription": {
                    "type": "object",
                    "properties": {
                        "id": {
                            "type": "string"
                        },
                        "plan": {
                            "type": "object",
                            "properties": {
                                "frequency": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "recurrences": {
                                    "type": "integer"
                                }
                            }
                        },
                        "status": {
                            "type": "string"
                        }
                    }
                },
                "subscription_id": {
                    "type": "string"
                },
                "tracking_data": {
                    "type": "object",
                    "properties": {
                        "campaign": {
                            "type": "string"
                        },
                        "content": {
                            "type": "string"
                        },
                        "identifier": {
                            "type": "string"
                        },
                        "medium": {
                            "type": "string"
                        },
                        "segment_name": {
                            "type": "string"
                        },
                        "source": {
                            "type": "string"
                        },
                        "term": {
                            "type": "string"
                        },
                        "utm_campaign": {
                            "type": "string"
                        },
                        "utm_content": {
                            "type": "string"
                        },
                        "utm_medium": {
                            "type": "string"
                        },
                        "utm_source": {
                            "type": "string"
                        },
                        "utm_term": {
                            "type": "string"
                        }
                    }
                },
                "webhook_event_id": {
                    "type": "string"
                },
                "webhook_event_type": {
                    "type": "string"
                }
            }
        },
        "models.MetaAdsData": {
            "type": "object",
            "properties": {
                "cac": {
                    "description": "Custo de Aquisição por Cliente",
                    "type": "number"
                },
                "campanha_id": {
                    "type": "string"
                },
                "campanha_nome": {
                    "type": "string"
                },
                "ctr": {
                    "description": "Click-Through Rate",
                    "type": "number"
                },
                "data_fim": {
                    "type": "string"
                },
                "data_inicio": {
                    "type": "string"
                },
                "investimento": {
                    "description": "Investimento Total",
                    "type": "number"
                },
                "numero_vendas": {
                    "description": "Número de Vendas",
                    "type": "integer"
                }
            }
        },
        "models.MetaAdsRequest": {
            "type": "object",
            "required": [
                "token"
            ],
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.MetaAdsResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.MetaAdsData"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "description": "Endpoints para integração com Meta Ads",
            "name": "Meta Ads"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Webhooks e Integrações",
	Description:      "API para receber webhooks da Kiwify, Hotmart, Kirvano e integração com Meta Ads",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
